const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        PostCategory: {
            $name: "Work"
        },
        PostTodo: {
            $name: "Meeting",
            $description: "Starts at 9am",
            $categoryId: 1,
            $statusId: 1
        },
        PutCategory: {
            $name: "Home"
        },
        Login: {
            $email: "user@example.com",
            $password: "P4ssword"
        },
        Signup: {
            $name: "User",
            $email: "user@example.com",
            $password: "P4ssword"
        },
        DeleteUser: {
            $email: "user@example.com"
        },
        PutTodo: {
            $description: "Starts at 11am"
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})